//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Oereb.Service.DataContracts.Model
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Versioning")
    ]
    [System.Xml.Serialization.XmlRootAttribute("GetVersionsResponse",
        Namespace = "http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Versioning", IsNullable = false)]
    public partial class GetVersionsResponseType
    {

        private VersionType[] supportedVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supportedVersion")]
        public VersionType[] supportedVersion
        {
            get { return this.supportedVersionField; }
            set { this.supportedVersionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Versioning")
    ]
    public partial class VersionType
    {

        private string versionField;

        private string serviceEndpointBaseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string version
        {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string serviceEndpointBase
        {
            get { return this.serviceEndpointBaseField; }
            set { this.serviceEndpointBaseField = value; }
        }
    }
}
