//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Oereb.Service.DataContracts.Model.v10
{

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", IsNullable=false)]
public partial class extensions {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class ExclusionOfLiability {
    
    private LocalisedText[] titleField;
    
    private LocalisedMText[] contentField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class LocalisedText {
    
    private LanguageCode languageField;
    
    private bool languageFieldSpecified;
    
    private string textField;
    
    /// <remarks/>
    public LanguageCode Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {
        get {
            return this.languageFieldSpecified;
        }
        set {
            this.languageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public enum LanguageCode {
    
    /// <remarks/>
    de,
    
    /// <remarks/>
    fr,
    
    /// <remarks/>
    it,
    
    /// <remarks/>
    rm,
    
    /// <remarks/>
    en,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class LocalisedMText {
    
    private LanguageCode languageField;
    
    private bool languageFieldSpecified;
    
    private string textField;
    
    /// <remarks/>
    public LanguageCode Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {
        get {
            return this.languageFieldSpecified;
        }
        set {
            this.languageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class LocalisedUri {
    
    private LanguageCode languageField;
    
    private bool languageFieldSpecified;
    
    private string textField;
    
    /// <remarks/>
    public LanguageCode Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {
        get {
            return this.languageFieldSpecified;
        }
        set {
            this.languageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Article))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class DocumentBase {
    
    private DocumentBaseDocumentType documentTypeField;
    
    private LocalisedUri[] textAtWebField;
    
    private Lawstatus lawstatusField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    public DocumentBaseDocumentType DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedUri[] TextAtWeb {
        get {
            return this.textAtWebField;
        }
        set {
            this.textAtWebField = value;
        }
    }
    
    /// <remarks/>
    public Lawstatus Lawstatus {
        get {
            return this.lawstatusField;
        }
        set {
            this.lawstatusField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public enum DocumentBaseDocumentType {
    
    /// <remarks/>
    LegalProvision,
    
    /// <remarks/>
    Law,
    
    /// <remarks/>
    Hint,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Lawstatus {
    
    private LawstatusCode codeField;
    
    private LocalisedText textField;
    
    /// <remarks/>
    public LawstatusCode Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public LocalisedText Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public enum LawstatusCode {
    
    /// <remarks/>
    inForce,
    
    /// <remarks/>
    runningModifications,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Document : DocumentBase {
    
    private LocalisedText[] titleField;
    
    private LocalisedText[] officialTitleField;
    
    private LocalisedText[] abbreviationField;
    
    private string officialNumberField;
    
    private CantonCode cantonField;
    
    private bool cantonFieldSpecified;
    
    private string municipalityField;
    
    private Office responsibleOfficeField;
    
    private string[] articleNumberField;
    
    private Article[] articleField;
    
    private Document[] referenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] OfficialTitle {
        get {
            return this.officialTitleField;
        }
        set {
            this.officialTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] Abbreviation {
        get {
            return this.abbreviationField;
        }
        set {
            this.abbreviationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OfficialNumber {
        get {
            return this.officialNumberField;
        }
        set {
            this.officialNumberField = value;
        }
    }
    
    /// <remarks/>
    public CantonCode Canton {
        get {
            return this.cantonField;
        }
        set {
            this.cantonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CantonSpecified {
        get {
            return this.cantonFieldSpecified;
        }
        set {
            this.cantonFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    public Office ResponsibleOffice {
        get {
            return this.responsibleOfficeField;
        }
        set {
            this.responsibleOfficeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArticleNumber", DataType="normalizedString")]
    public string[] ArticleNumber {
        get {
            return this.articleNumberField;
        }
        set {
            this.articleNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Article")]
    public Article[] Article {
        get {
            return this.articleField;
        }
        set {
            this.articleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public Document[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    [XmlIgnoreAttribute]
    public int SortLevel { get; set; } = 0;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public enum CantonCode {
    
    /// <remarks/>
    ZH,
    
    /// <remarks/>
    BE,
    
    /// <remarks/>
    LU,
    
    /// <remarks/>
    UR,
    
    /// <remarks/>
    SZ,
    
    /// <remarks/>
    OW,
    
    /// <remarks/>
    NW,
    
    /// <remarks/>
    GL,
    
    /// <remarks/>
    ZG,
    
    /// <remarks/>
    FR,
    
    /// <remarks/>
    SO,
    
    /// <remarks/>
    BS,
    
    /// <remarks/>
    BL,
    
    /// <remarks/>
    SH,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    AI,
    
    /// <remarks/>
    SG,
    
    /// <remarks/>
    GR,
    
    /// <remarks/>
    AG,
    
    /// <remarks/>
    TG,
    
    /// <remarks/>
    TI,
    
    /// <remarks/>
    VD,
    
    /// <remarks/>
    VS,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    GE,
    
    /// <remarks/>
    JU,
    
    /// <remarks/>
    FL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Office {
    
    private LocalisedText[] nameField;
    
    private WebReference officeAtWebField;
    
    private string uIDField;
    
    private string line1Field;
    
    private string line2Field;
    
    private string streetField;
    
    private string numberField;
    
    private string postalCodeField;
    
    private string cityField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public WebReference OfficeAtWeb {
        get {
            return this.officeAtWebField;
        }
        set {
            this.officeAtWebField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Line1 {
        get {
            return this.line1Field;
        }
        set {
            this.line1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Line2 {
        get {
            return this.line2Field;
        }
        set {
            this.line2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class WebReference {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Article : DocumentBase {
    
    private string numberField;
    
    private LocalisedMText[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class LegendEntry {
    
    private object itemField;
    
    private LocalisedText[] legendTextField;
    
    private string typeCodeField;
    
    private string typeCodelistField;
    
    private Theme themeField;
    
    private string subThemeField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("SymbolRef", typeof(string), DataType="anyURI")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] LegendText {
        get {
            return this.legendTextField;
        }
        set {
            this.legendTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TypeCode {
        get {
            return this.typeCodeField;
        }
        set {
            this.typeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string TypeCodelist {
        get {
            return this.typeCodelistField;
        }
        set {
            this.typeCodelistField = value;
        }
    }
    
    /// <remarks/>
    public Theme Theme {
        get {
            return this.themeField;
        }
        set {
            this.themeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubTheme {
        get {
            return this.subThemeField;
        }
        set {
            this.subThemeField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Theme {
    
    private string codeField;
    
    private LocalisedText textField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public LocalisedText Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Map {
    
    private byte[] imageField;
    
    private string referenceWMSField;
    
    private WebReference legendAtWebField;
    
    private LegendEntry[] otherLegendField;
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string layerIndexField;
    
    private double layerOpacityField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string ReferenceWMS {
        get {
            return this.referenceWMSField;
        }
        set {
            this.referenceWMSField = value;
        }
    }
    
    /// <remarks/>
    public WebReference LegendAtWeb {
        get {
            return this.legendAtWebField;
        }
        set {
            this.legendAtWebField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OtherLegend")]
    public LegendEntry[] OtherLegend {
        get {
            return this.otherLegendField;
        }
        set {
            this.otherLegendField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("max_NS03", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("max_NS95", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("min_NS03", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("min_NS95", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string layerIndex {
        get {
            return this.layerIndexField;
        }
        set {
            this.layerIndexField = value;
        }
    }
    
    /// <remarks/>
    public double layerOpacity {
        get {
            return this.layerOpacityField;
        }
        set {
            this.layerOpacityField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    max_NS03,
    
    /// <remarks/>
    max_NS95,
    
    /// <remarks/>
    min_NS03,
    
    /// <remarks/>
    min_NS95,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Geometry {
    
    private XElement itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private Lawstatus lawstatusField;
    
    private string metadataOfGeographicalBaseDataField;
    
    private Office responsibleOfficeField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Point", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Surface", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string ItemGeometryLOLS //TODO remove this element 
    {
        get { return this.itemField.ToString(); }
        set { this.itemField = XElement.Parse(value); }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public Lawstatus Lawstatus {
        get {
            return this.lawstatusField;
        }
        set {
            this.lawstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string MetadataOfGeographicalBaseData {
        get {
            return this.metadataOfGeographicalBaseDataField;
        }
        set {
            this.metadataOfGeographicalBaseDataField = value;
        }
    }
    
    /// <remarks/>
    public Office ResponsibleOffice {
        get {
            return this.responsibleOfficeField;
        }
        set {
            this.responsibleOfficeField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Line,
    
    /// <remarks/>
    Point,
    
    /// <remarks/>
    Surface,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class RestrictionOnLandownership {
    
    private LocalisedMText[] informationField;
    
    private Theme themeField;
    
    private string subThemeField;
    
    private string typeCodeField;
    
    private string typeCodelistField;
    
    private Lawstatus lawstatusField;
    
    private string areaShareField;
    
    private string lengthShareField;
    
    private string nrOfPointsField;
    
    private double partInPercentField;
    
    private bool partInPercentFieldSpecified;
    
    private object itemField;
    
    private Geometry[] geometryField;
    
    private Map mapField;
    
    private DocumentBase[] legalProvisionsField;
    
    private Office responsibleOfficeField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] Information {
        get {
            return this.informationField;
        }
        set {
            this.informationField = value;
        }
    }
    
    /// <remarks/>
    public Theme Theme {
        get {
            return this.themeField;
        }
        set {
            this.themeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubTheme {
        get {
            return this.subThemeField;
        }
        set {
            this.subThemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TypeCode {
        get {
            return this.typeCodeField;
        }
        set {
            this.typeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string TypeCodelist {
        get {
            return this.typeCodelistField;
        }
        set {
            this.typeCodelistField = value;
        }
    }
    
    /// <remarks/>
    public Lawstatus Lawstatus {
        get {
            return this.lawstatusField;
        }
        set {
            this.lawstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string AreaShare {
        get {
            return this.areaShareField;
        }
        set {
            this.areaShareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string LengthShare {
        get {
            return this.lengthShareField;
        }
        set {
            this.lengthShareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NrOfPoints {
        get {
            return this.nrOfPointsField;
        }
        set {
            this.nrOfPointsField = value;
        }
    }
    
    /// <remarks/>
    public double PartInPercent {
        get {
            return this.partInPercentField;
        }
        set {
            this.partInPercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PartInPercentSpecified {
        get {
            return this.partInPercentFieldSpecified;
        }
        set {
            this.partInPercentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("SymbolRef", typeof(string), DataType="anyURI")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Geometry")]
    public Geometry[] Geometry {
        get {
            return this.geometryField;
        }
        set {
            this.geometryField = value;
        }
    }
    
    /// <remarks/>
    public Map Map {
        get {
            return this.mapField;
        }
        set {
            this.mapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LegalProvisions")]
    public DocumentBase[] LegalProvisions {
        get {
            return this.legalProvisionsField;
        }
        set {
            this.legalProvisionsField = value;
        }
    }
    
    /// <remarks/>
    public Office ResponsibleOffice {
        get {
            return this.responsibleOfficeField;
        }
        set {
            this.responsibleOfficeField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class RealEstate_DPR {
    
    private string numberField;
    
    private string identDNField;
    
    private string eGRIDField;
    
    private RealEstateType typeField;
    
    private CantonCode cantonField;
    
    private string municipalityField;
    
    private string subunitOfLandRegisterField;
    
    private string fosNrField;
    
    private string metadataOfGeographicalBaseDataField;
    
    private string landRegistryAreaField;
    
    private string limitField;
    
    private RestrictionOnLandownership[] restrictionOnLandownershipField;
    
    private Map planForLandRegisterField;
    
    private Map planForLandRegisterMainPageField;
    
    private Document[] referenceField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IdentDN {
        get {
            return this.identDNField;
        }
        set {
            this.identDNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EGRID {
        get {
            return this.eGRIDField;
        }
        set {
            this.eGRIDField = value;
        }
    }
    
    /// <remarks/>
    public RealEstateType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public CantonCode Canton {
        get {
            return this.cantonField;
        }
        set {
            this.cantonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubunitOfLandRegister {
        get {
            return this.subunitOfLandRegisterField;
        }
        set {
            this.subunitOfLandRegisterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string FosNr {
        get {
            return this.fosNrField;
        }
        set {
            this.fosNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string MetadataOfGeographicalBaseData {
        get {
            return this.metadataOfGeographicalBaseDataField;
        }
        set {
            this.metadataOfGeographicalBaseDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string LandRegistryArea {
        get {
            return this.landRegistryAreaField;
        }
        set {
            this.landRegistryAreaField = value;
        }
    }
    
    /// <remarks/>
    public string Limit {
        get {
            return this.limitField;
        }
        set {
            this.limitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RestrictionOnLandownership")]
    public RestrictionOnLandownership[] RestrictionOnLandownership {
        get {
            return this.restrictionOnLandownershipField;
        }
        set {
            this.restrictionOnLandownershipField = value;
        }
    }
    
    /// <remarks/>
    public Map PlanForLandRegister {
        get {
            return this.planForLandRegisterField;
        }
        set {
            this.planForLandRegisterField = value;
        }
    }
    
    /// <remarks/>
    public Map PlanForLandRegisterMainPage {
        get {
            return this.planForLandRegisterMainPageField;
        }
        set {
            this.planForLandRegisterMainPageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public Document[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public enum RealEstateType {
    
    /// <remarks/>
    RealEstate,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.BuildingRight")]
    Distinct_and_permanent_rightsBuildingRight,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.right_to_spring_water")]
    Distinct_and_permanent_rightsright_to_spring_water,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.concession")]
    Distinct_and_permanent_rightsconcession,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.other")]
    Distinct_and_permanent_rightsother,
    
    /// <remarks/>
    Mineral_rights,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
public partial class Glossary {
    
    private LocalisedText[] titleField;
    
    private LocalisedMText[] contentField;
    
    private extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocalisedText[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", IsNullable=false)]
public partial class Extract {
    
    private System.DateTime creationDateField;
    
    private Theme[] concernedThemeField;
    
    private Theme[] notConcernedThemeField;
    
    private Theme[] themeWithoutDataField;
    
    private bool isReducedField;
    
    private object itemField;
    
    private object item1Field;
    
    private object item2Field;
    
    private object item3Field;
    
    private string extractIdentifierField;
    
    private object item4Field;
    
    private LocalisedMText[] generalInformationField;
    
    private LocalisedMText[] baseDataField;
    
    private Glossary[] glossaryField;
    
    private RealEstate_DPR realEstateField;
    
    private ExclusionOfLiability[] exclusionOfLiabilityField;
    
    private Office pLRCadastreAuthorityField;
    
    private LocalisedMText[] certificationField;
    
    private LocalisedUri[] certificationAtWebField;
    
    private extensions extensionsField;
    
    private string idField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public System.DateTime CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ConcernedTheme")]
    public Theme[] ConcernedTheme {
        get {
            return this.concernedThemeField;
        }
        set {
            this.concernedThemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NotConcernedTheme")]
    public Theme[] NotConcernedTheme {
        get {
            return this.notConcernedThemeField;
        }
        set {
            this.notConcernedThemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ThemeWithoutData")]
    public Theme[] ThemeWithoutData {
        get {
            return this.themeWithoutDataField;
        }
        set {
            this.themeWithoutDataField = value;
        }
    }
    
    /// <remarks/>
    public bool isReduced {
        get {
            return this.isReducedField;
        }
        set {
            this.isReducedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LogoPLRCadastre", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("LogoPLRCadastreRef", typeof(string), DataType="anyURI")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FederalLogo", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("FederalLogoRef", typeof(string), DataType="anyURI")]
    public object Item1 {
        get {
            return this.item1Field;
        }
        set {
            this.item1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CantonalLogo", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("CantonalLogoRef", typeof(string), DataType="anyURI")]
    public object Item2 {
        get {
            return this.item2Field;
        }
        set {
            this.item2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MunicipalityLogo", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("MunicipalityLogoRef", typeof(string), DataType="anyURI")]
    public object Item3 {
        get {
            return this.item3Field;
        }
        set {
            this.item3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ExtractIdentifier {
        get {
            return this.extractIdentifierField;
        }
        set {
            this.extractIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QRCode", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("QRCodeRef", typeof(string), DataType="anyURI")]
    public object Item4 {
        get {
            return this.item4Field;
        }
        set {
            this.item4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] GeneralInformation {
        get {
            return this.generalInformationField;
        }
        set {
            this.generalInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] BaseData {
        get {
            return this.baseDataField;
        }
        set {
            this.baseDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Glossary")]
    public Glossary[] Glossary {
        get {
            return this.glossaryField;
        }
        set {
            this.glossaryField = value;
        }
    }
    
    /// <remarks/>
    public RealEstate_DPR RealEstate {
        get {
            return this.realEstateField;
        }
        set {
            this.realEstateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExclusionOfLiability")]
    public ExclusionOfLiability[] ExclusionOfLiability {
        get {
            return this.exclusionOfLiabilityField;
        }
        set {
            this.exclusionOfLiabilityField = value;
        }
    }
    
    /// <remarks/>
    public Office PLRCadastreAuthority {
        get {
            return this.pLRCadastreAuthorityField;
        }
        set {
            this.pLRCadastreAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedMText[] Certification {
        get {
            return this.certificationField;
        }
        set {
            this.certificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
    public LocalisedUri[] CertificationAtWeb {
        get {
            return this.certificationAtWebField;
        }
        set {
            this.certificationAtWebField = value;
        }
    }
    
    /// <remarks/>
    public extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}
}